# Generated by Django 3.0.8 on 2020-11-21 13:25

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_order_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name=mainapp.models.CartProduct),
            preserve_default=False,
        ),
    ]
