# Generated by Django 3.0.8 on 2020-11-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
    ]
