# Generated by Django 3.0.8 on 2020-11-21 13:29

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_cart_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name=mainapp.models.CartProduct),
        ),
    ]
