# Generated by Django 3.0.8 on 2020-11-21 13:35

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20201121_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name=mainapp.models.Cart),
        ),
    ]
